# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.3.2/www/docs/static/schema.json

version: 2
project_name: goarkitect
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.gitCommit={{ .Commit }}
      - -X main.buildTime={{ .Date }}
      - -X main.goVersion={{ .Env.GO_VERSION }}
      - -X main.osArch={{ .Arch }}
archives:
  - name_template: "{{ tolower .ProjectName }}-{{ tolower .Os }}-{{ tolower .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Branch }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: omissis
    name: goarkitect
  name_template: "{{ .Tag }}"
  prerelease: auto
brews:
  - name: goarkitect
    repository:
      owner: omissis
      name: homebrew-goarkitect
    skip_upload: auto
    directory: Formula
    homepage: "https://gihub.com/omissis/goarkitect"
    description: "Goarkitect binary"
    test: |
      system "#{bin}/goarkitect"
    install: |
      bin.install 'goarkitect'
dockers:
  - image_templates:
      - "ghcr.io/omissis/goarkitect:latest-amd64"
      - "ghcr.io/omissis/goarkitect:{{ .Version }}-amd64"
      - "ghcr.io/omissis/goarkitect:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/omissis/goarkitect:{{ .Major }}-amd64"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--target=goreleaser"
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
    skip_push: auto
  - image_templates:
      - "ghcr.io/omissis/goarkitect:latest-arm64"
      - "ghcr.io/omissis/goarkitect:{{ .Version }}-arm64"
      - "ghcr.io/omissis/goarkitect:{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/omissis/goarkitect:{{ .Major }}-arm64"
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--target=goreleaser"
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
    skip_push: auto
docker_manifests:
  - name_template: "ghcr.io/omissis/goarkitect:latest"
    image_templates:
      - "ghcr.io/omissis/goarkitect:latest-amd64"
      - "ghcr.io/omissis/goarkitect:latest-arm64"
    skip_push: auto
  - name_template: "ghcr.io/omissis/goarkitect:{{ .Version }}"
    image_templates:
      - "ghcr.io/omissis/goarkitect:{{ .Version }}-amd64"
      - "ghcr.io/omissis/goarkitect:{{ .Version }}-arm64"
    skip_push: auto
  - name_template: "ghcr.io/omissis/goarkitect:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/omissis/goarkitect:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/omissis/goarkitect:{{ .Major }}.{{ .Minor }}-arm64"
    skip_push: auto
  - name_template: "ghcr.io/omissis/goarkitect:{{ .Major }}"
    image_templates:
      - "ghcr.io/omissis/goarkitect:{{ .Major }}-amd64"
      - "ghcr.io/omissis/goarkitect:{{ .Major }}-arm64"
    skip_push: auto
